name: Dependencies

on:
  schedule:
    # Monthly on the 1st at 3 AM UTC
    - cron: '0 3 1 * *'
  workflow_dispatch:
    inputs:
      create_pr:
        description: 'Create pull request with updates'
        type: boolean
        default: true

concurrency:
  group: dependencies
  cancel-in-progress: true

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyyaml
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Update Dependencies
      working-directory: python
      run: ./ci deps
      env:
        CI_ENVIRONMENT: ci
    
    - name: Create Pull Request
      if: ${{ inputs.create_pr || github.event_name == 'schedule' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies (automated)'
        title: 'Automated Dependency Updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates created by the streamlined CI/CD system.
          
          ### Changes
          - Updated Python dependencies in `requirements.txt`
          - Updated Ruby dependencies via `bundle update` (if applicable)
          
          ### Testing
          - [x] Dependencies installed successfully
          - [x] Basic functionality verified
          
          🤖 Generated by CI/CD System
        branch: dependency-updates-streamlined
        branch-suffix: timestamp
        delete-branch: true
    
    - name: Upload Dependency Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-reports
        path: ci-reports/
        retention-days: 30