name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to create'
        required: true
        type: string
      draft:
        description: 'Create draft release'
        type: boolean
        default: false

concurrency:
  group: release
  cancel-in-progress: false  # Don't cancel releases

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for changelog
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyyaml
    
    - name: Get Release Version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION=${{ inputs.tag }}
        else
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "draft=${{ inputs.draft || 'false' }}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      working-directory: python
      run: |
        if [ "${{ steps.version.outputs.draft }}" = "true" ]; then
          ./ci release ${{ steps.version.outputs.version }} --draft
        else
          ./ci release ${{ steps.version.outputs.version }}
        fi
      env:
        CI_ENVIRONMENT: ci
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Release Assets
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: release-assets
        path: |
          ci-reports/
          dist/
        retention-days: 90